apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zabbix
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
      - pods
    verbs:
      - list
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - list
      - get
