apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: cluster
servers: 1
agents: 3
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --node-taint=node-role.kubernetes.io/master=:NoSchedule
        nodeFilters:
          - server:*
  runtime:
    serversMemory: 1G
    agentsMemory: 1G
